In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from imblearn.metrics import classification_report_imbalanced

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df_lending_data = pd.read_csv(Path("Resources/lending_data.csv"))

# Display sample data
df_lending_data.head(10)

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   
5    10100.0          7.438            50600        0.407115                4   
6    10300.0          7.490            51100        0.412916                4   
7     8800.0          6.857            45100        0.334812                3   
8     9300.0          7.096            47400        0.367089                3   
9     9700.0          7.248            48800        0.385246                4   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0  
5                 1       20600            0  
6                 1       21100            0  
7                 0       15100            0  
8                 0       17400            0  
9                 0       18800            0

In [3]:
y = df_lending_data['loan_status']
X = df_lending_data.drop(columns='loan_status')
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [4]:
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [5]:
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

In [6]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
# Declare a logistic regression model.
# Apply a random_state of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)
# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

In [8]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [10]:
# Display the accuracy score for the test dataset.
accuracy_score(y_test, testing_predictions)

0.9915394139496492

In [14]:
# Import the model for sklearn's confusion matrix
from sklearn.metrics import confusion_matrix

 # Create and save the confustion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[18669    92]
 [   72   551]]


In [15]:
 # Create and save the training classifiction report
testing_report = classification_report(y_test, testing_predictions)

# Print the training classification report
print(testing_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18761
           1       0.86      0.88      0.87       623

    accuracy                           0.99     19384
   macro avg       0.93      0.94      0.93     19384
weighted avg       0.99      0.99      0.99     19384



In [17]:
###Predict a Logistic Regression Model with Resampled Training Data


In [19]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate a RandomOversampler instance
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
# Fit the model to the training data
X_oversampled, y_oversampled = ros.fit_resample(X_train, y_train)

In [21]:
 # Count distinct values
y_oversampled.value_counts()

0    56275
1    56275
Name: loan_status, dtype: int64

In [22]:
# Declare a logistic regression model.
# Apply a random_state of 1 to the model
logistic_regression_model1 = LogisticRegression(random_state=1)

In [23]:
 # Fit and save the logistic regression model using the training data
lr_model1 = logistic_regression_model1.fit(X_train, y_train)

In [25]:
training_predictions = lr_model1.predict(X_train)

# Review the predictions
training_predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
accuracy_score(y_train, training_predictions)

0.9921240885954051

In [28]:
# Import the model for sklearn's confusion matrix
from sklearn.metrics import confusion_matrix

 # Create and save the confustion matrix for the testing data
train_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the testing data
print(train_matrix)

[[55988   287]
 [  171  1706]]


In [29]:
 # Create and save the training classifiction report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56275
           1       0.86      0.91      0.88      1877

    accuracy                           0.99     58152
   macro avg       0.93      0.95      0.94     58152
weighted avg       0.99      0.99      0.99     58152

